# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test-nbdev-mkdocs',
                'doc_host': 'https://harishmohanraj.github.io',
                'git_url': 'https://github.com/harishmohanraj/test-nbdev-mkdocs',
                'lib_path': 'test_nbdev_mkdocs'},
  'syms': {'test_nbdev_mkdocs.core': {'test_nbdev_mkdocs.core.foo': ('core.html#foo', 'test_nbdev_mkdocs/core.py')}}}
